"""
Definitive AI marker detection.

This module detects DEFINITIVE signals of AI generation - not heuristics,
but actual proof like explicit attribution, known AI tool files, and
AI author markers.

These signals should be weighted extremely heavily as they represent
concrete evidence rather than statistical inference.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from ..models import DetectionSignal


# Files that definitively indicate AI tool usage
AI_MARKER_FILES = {
    # Claude Code
    "claude.md": ("Claude Code configuration file", 0.95),
    ".claude": ("Claude configuration directory", 0.95),
    ".claude/settings.json": ("Claude settings file", 0.95),
    ".claude/commands": ("Claude custom commands", 0.90),

    # GitHub Copilot
    ".github/copilot-instructions.md": ("Copilot instructions file", 0.90),
    ".copilot": ("Copilot configuration", 0.85),

    # Cursor AI
    ".cursor": ("Cursor AI configuration", 0.90),
    ".cursorrules": ("Cursor AI rules file", 0.90),
    ".cursorignore": ("Cursor AI ignore file", 0.85),

    # Aider
    ".aider": ("Aider AI configuration", 0.90),
    ".aider.conf.yml": ("Aider configuration", 0.90),
    ".aiderignore": ("Aider ignore file", 0.85),

    # Codeium
    ".codeium": ("Codeium AI configuration", 0.85),

    # Generic AI
    ".ai": ("AI configuration directory", 0.80),
    "ai-instructions.md": ("AI instructions file", 0.85),
}

# Patterns in file content that definitively indicate AI generation
AI_CONTENT_MARKERS = [
    # Claude markers
    (r"🤖\s*Generated with \[Claude", "Claude Code generation marker", 0.98),
    (r"Generated with Claude Code", "Claude Code attribution", 0.98),
    (r"Co-Authored-By:\s*Claude", "Claude co-author attribution", 0.95),
    (r"Co-Authored-By:.*<noreply@anthropic\.com>", "Anthropic co-author email", 0.98),
    (r"@anthropic\.com", "Anthropic email in attribution", 0.90),

    # GitHub Copilot markers
    (r"Generated by GitHub Copilot", "Copilot generation marker", 0.95),
    (r"Co-Authored-By:.*Copilot", "Copilot co-author", 0.95),
    (r"Co-Authored-By:.*<copilot@github\.com>", "Copilot email attribution", 0.98),
    (r"GitHub Copilot suggested", "Copilot suggestion marker", 0.85),

    # ChatGPT/OpenAI markers
    (r"Generated by ChatGPT", "ChatGPT generation marker", 0.95),
    (r"Generated by GPT-?4", "GPT-4 generation marker", 0.95),
    (r"Co-Authored-By:.*OpenAI", "OpenAI co-author", 0.90),
    (r"Written by AI assistant", "Generic AI attribution", 0.85),

    # Cursor AI markers
    (r"Generated by Cursor", "Cursor generation marker", 0.95),

    # Aider markers
    (r"aider:", "Aider commit marker", 0.90),

    # Generic AI markers
    (r"AI-generated", "Generic AI-generated marker", 0.85),
    (r"Generated by AI", "Generic AI generation", 0.85),
    (r"This (?:code|file) was (?:generated|written|created) (?:by|with|using) (?:an? )?(?:AI|LLM|GPT|Claude|Copilot)", "AI generation statement", 0.90),

    # Common AI commit message patterns
    (r"🤖.*Generated", "Robot emoji with Generated", 0.90),
    (r"✨.*(?:AI|Claude|Copilot|GPT)", "Sparkle emoji with AI tool", 0.75),
]

# Author patterns that indicate AI
AI_AUTHOR_PATTERNS = [
    (r"^claude$", "Author named 'claude'", 0.95),
    (r"^copilot$", "Author named 'copilot'", 0.95),
    (r"^github.?copilot$", "Author named 'github-copilot'", 0.98),
    (r"^gpt$", "Author named 'gpt'", 0.90),
    (r"^chatgpt$", "Author named 'chatgpt'", 0.95),
    (r"^openai$", "Author named 'openai'", 0.90),
    (r"^cursor$", "Author named 'cursor'", 0.85),
    (r"^aider$", "Author named 'aider'", 0.90),
    (r"^ai-?assistant$", "Author named 'ai-assistant'", 0.90),
    (r"^codeium$", "Author named 'codeium'", 0.85),
    (r"anthropic", "Author containing 'anthropic'", 0.90),
    (r"noreply@anthropic", "Anthropic noreply email", 0.95),
    (r"copilot@github", "Copilot GitHub email", 0.98),
]


@dataclass
class DefinitiveConfig:
    """Configuration for definitive detection."""
    # Minimum score to consider a signal "definitive"
    definitive_threshold: float = 0.85


class DefinitiveDetector:
    """
    Detect definitive markers of AI generation.

    Unlike heuristic detection, these are concrete signals like:
    - AI tool configuration files (CLAUDE.md, .cursorrules)
    - Explicit AI attribution in commits
    - AI author/contributor names
    - Generation markers in content
    """

    def __init__(self, config: Optional[DefinitiveConfig] = None):
        self.config = config or DefinitiveConfig()

    def check_filename(self, path: Path) -> list[DetectionSignal]:
        """Check if a filename indicates AI tool usage."""
        signals = []
        path_str = str(path).lower()
        filename = path.name.lower()

        for marker_path, (description, score) in AI_MARKER_FILES.items():
            if path_str.endswith(marker_path) or filename == marker_path:
                signals.append(DetectionSignal(
                    name=f"AI marker file: {marker_path}",
                    score=score,
                    weight=0.95,  # Very high weight - this is definitive
                    description=description,
                    evidence=[str(path)]
                ))

        return signals

    def check_content(self, content: str, filename: str = "") -> list[DetectionSignal]:
        """Check content for definitive AI markers."""
        signals = []

        for pattern, name, score in AI_CONTENT_MARKERS:
            matches = re.findall(pattern, content, re.IGNORECASE | re.MULTILINE)
            if matches:
                signals.append(DetectionSignal(
                    name=name,
                    score=score,
                    weight=0.95,  # Very high weight
                    description=f"Found {len(matches)} instance(s) of definitive AI marker",
                    evidence=[m if isinstance(m, str) else str(m) for m in matches[:3]]
                ))

        return signals

    def check_commit(self, commit: dict) -> list[DetectionSignal]:
        """Check a commit for definitive AI markers."""
        signals = []

        message = commit.get("message", "")
        author = commit.get("author", "").lower()
        author_email = commit.get("author_email", "").lower()

        # Check commit message for AI markers
        for pattern, name, score in AI_CONTENT_MARKERS:
            if re.search(pattern, message, re.IGNORECASE):
                signals.append(DetectionSignal(
                    name=f"Commit: {name}",
                    score=score,
                    weight=0.95,
                    description=f"Commit message contains AI marker",
                    evidence=[message[:100]]
                ))

        # Check author name
        for pattern, name, score in AI_AUTHOR_PATTERNS:
            if re.search(pattern, author, re.IGNORECASE):
                signals.append(DetectionSignal(
                    name=f"AI Author: {name}",
                    score=score,
                    weight=0.95,
                    description=f"Commit author matches AI pattern",
                    evidence=[author]
                ))

            if re.search(pattern, author_email, re.IGNORECASE):
                signals.append(DetectionSignal(
                    name=f"AI Author Email: {name}",
                    score=score,
                    weight=0.95,
                    description=f"Commit author email matches AI pattern",
                    evidence=[author_email]
                ))

        return signals

    def analyze_commits(self, commits: list[dict]) -> tuple[list[DetectionSignal], dict]:
        """
        Analyze all commits for AI markers.

        Returns:
            Tuple of (signals, stats) where stats contains:
            - ai_commits: number of commits with AI markers
            - ai_commit_ratio: ratio of AI commits to total
            - ai_authors: set of AI author names found
        """
        all_signals = []
        ai_commits = 0
        ai_authors = set()

        for commit in commits:
            commit_signals = self.check_commit(commit)
            if commit_signals:
                ai_commits += 1
                all_signals.extend(commit_signals)

                author = commit.get("author", "").lower()
                for pattern, _, _ in AI_AUTHOR_PATTERNS:
                    if re.search(pattern, author, re.IGNORECASE):
                        ai_authors.add(commit.get("author", ""))

        # Add summary signal if significant AI commit presence
        if commits and ai_commits > 0:
            ratio = ai_commits / len(commits)
            if ratio > 0.1:  # More than 10% AI commits
                all_signals.append(DetectionSignal(
                    name="Significant AI commit ratio",
                    score=min(0.95, 0.5 + ratio * 0.5),
                    weight=0.9,
                    description=f"{ai_commits}/{len(commits)} commits ({ratio:.0%}) have AI markers",
                    evidence=[f"AI authors: {', '.join(ai_authors)}"] if ai_authors else []
                ))

        stats = {
            "ai_commits": ai_commits,
            "total_commits": len(commits),
            "ai_commit_ratio": ai_commits / len(commits) if commits else 0,
            "ai_authors": ai_authors,
        }

        return all_signals, stats

    def scan_repository_markers(self, file_paths: list[Path]) -> list[DetectionSignal]:
        """
        Scan all file paths for AI marker files.

        This is a quick scan of just filenames, not content.
        """
        signals = []

        for path in file_paths:
            signals.extend(self.check_filename(path))

        # Add summary if multiple markers found
        if len(signals) >= 2:
            signals.append(DetectionSignal(
                name="Multiple AI tool markers",
                score=0.95,
                weight=0.95,
                description=f"Found {len(signals)} AI tool marker files",
                evidence=[s.evidence[0] for s in signals[:5] if s.evidence]
            ))

        return signals
